# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15qX_V5bnjipu87f6rQWRD29XN536_okU

# Calculadora de Comissão do Vendedor
# Objetivo: Calcular valor que sera recebido de comissao
"""

# Interação com os Usuario
vendedor = input('Nome do vendedor:')
meta = float(input("Digite o valor da meta (R$): "))
vendas = float(input('Digite o valor das vendas R$:'))
percentual_comissao = float(input('Digite o percentual da comissao:'))

# Calculo
comissao = vendas * percentual_comissao / 100
atingimento_meta = (vendas / meta) * 100

# Exibição dos Resultados
print("\n=== RELATÓRIO DE COMISSÃO ===")
print(f"Vendedor: {vendedor}")
print(f"Valor das Vendas: R$ {vendas:.2f}")
print(f"Valor da Comissão: R$ {comissao:.2f}")
print(f"Total Vendido: R$ {vendas:,.2f}")

# Mensagem de desempenho
if atingimento_meta >= 100:
    print(" Excelente! Meta batida!")
elif 80 <= atingimento_meta < 100:
    print(" Quase lá! Continue focado.")
else:
    print(" Abaixo da meta. Reveja suas estratégias.")